### ISSUE TITLE
It's a good start, I have some suggestions for improvements

### ISSUE THREAD

**Issue by skliffmueller** [QuadDamn/battlenet-api-wrapper#1]
Hello! I found your project from the Blizzard community forum and thought I'd forward some additional information to help you out.

I noticed the return types being set for all your API methods are `Promise<object>` when you'd start developing with this API, you will get typescript yelling that particular fields don't exist from your object. I'd suggest building out your typings a bit better. I know the Blizzard API is not the most consistent when it comes to data fields always existing, but is manageable.

Here is an example of what D3 Gamedata Leaderboard typings would look like:
```typescript
/**
 * Typedefs for D3 Gamedata API Responses
 */
declare module "battlenet-api-wrapper/d3-gamedata" {

    /**
     * @type TLink
     * @desc Defines a basic href link object, typically references the next detailed dataset
     */
    type TLink = {
        href: string;
    }
    /**
     * @type TSelfLink
     * @desc Identifies the API call in reference to current data
     */
    type TSelfLink = {
        self: TLink;
    }
    /**
     * @interface IBaseResponse
     * @desc The base default fields that will exist in every API response
     */
    interface IBaseResponse {
        _links: TSelfLink;
        last_update_time: string;
        generated_by: string;
    }

    /**
     * @type TSeasonState
     * @desc The season status
     */
    type TSeasonState = "active" | "inactive";
    /**
     * Data structure for "Season Index" /data/d3/season/
     *
     * @remark
     * {@link https://develop.battle.net/documentation/diablo-3/game-data-apis#mat-expansion-panel-header-14 | API Docs}
     *
     * @interface ISeasonIndex
     */
    export interface ISeasonIndex extends IBaseResponse {
        season: TLink[];
        current_season: number;
        service_current_season: number;
        service_season_state: TSeasonState;
    }

    /**
     * @type THeroClass
     * @desc Hero Classes
     */
    type THeroClass = "barbarian" | "crusader" | "dh" | "monk" | "wd" | "wizard" | "necromancer";
    /**
     * @interface ILeaderboard
     * @memberOf ISeason
     */
    export interface ILeaderboard {
        team_size?: number;
        hardcore?: boolean;
        hero_class_string?: THeroClass;
        ladder: TLink;
    }
    /**
     * Data structure for Season object from API "/data/d3/season/:id"
     *
     * @remark
     * {@link https://develop.battle.net/documentation/diablo-3/game-data-apis#mat-expansion-panel-header-21 | API Docs}
     *
     * @interface ISeason
     */
    export interface ISeason extends IBaseResponse {
        leaderboard: ILeaderboard[];
    }

    /**
     * @type TDataObject
     * @desc Data object structure
     */
    type TDataObject = {
        id: string;
        string?: string;
        number?: number;
        timestamp?: number;
    };
    /**
     * @type TLocaleObject
     * @desc Locale object structure
     */
    type TLocaleObject = {
        en_US?: string;
        es_MX?: string;
        pt_BR?: string;
        de_DE?: string;
        en_GB?: string;
        es_ES?: string;
        fr_FR?: string;
        it_IT?: string;
        pl_PL?: string;
        pt_PT?: string;
        ru_RU?: string;
        ko_KR?: string;
        zh_TW?: string;
        zh_CN?: string;
    };

    /**
     * @enum EColumnType
     * @desc Column types expressed as enum
     */
    enum EColumnType {
        STRING = "STRING",
        NUMBER = "NUMBER",
        SPAN_MS = "SPAN_MS",
        DATETIME = "DATETIME",
    }

    /**
     * Season Leaderboard Player object
     *
     * @interface ISeasonLeaderboardPlayer
     * @memberOf ISeasonLeaderboardRow
     * @memberOf ISeasonLeaderboard
     */
    export interface ISeasonLeaderboardPlayer {
        key: string;
        accountId: number;
        data: TDataObject[];
    }
    /**
     * Season Leaderboard row object
     *
     * @interface ISeasonLeaderboardRow
     * @memberOf ISeasonLeaderboard
     */
    export interface ISeasonLeaderboardRow {
        order: number;
        player: ISeasonLeaderboardPlayer;
        data: TDataObject[];
    }
    /**
     * Season Leaderboard column object
     *
     * @interface ISeasonLeaderboardColumn
     * @memberOf ISeasonLeaderboard
     */
    export interface ISeasonLeaderboardColumn {
        id: string;
        hidden: boolean;
        order: number;
        label: TLocaleObject;
        type: EColumnType;
    }
    /**
     * Season Leaderboard response object from API "/data/d3/:id/leaderboard/:leaderboard"
     *
     * @remark
     * {@link https://develop.battle.net/documentation/diablo-3/game-data-apis#mat-expansion-panel-header-21 | API Docs}
     *
     * @interface ISeasonLeaderboard
     */
    export interface ISeasonLeaderboard extends IBaseResponse {
        key: string;
        title: TLocaleObject;
        hardcore?: boolean;
        greater_rift?: boolean;
        greater_rift_solo_class: THeroClass;
        season: number;
        row: ISeasonLeaderboardRow[];
        column: ISeasonLeaderboardColumn[];
    }
}
```

You'd add these in as something like /src/d3/gamedata.d.ts and then you can import the type `import { ISeasonLeaderboard } from "gamedata.d"`

Then where you have your Leaderboard API https://github.com/QuadDamn/battlenet-api-wrapper/blob/master/src/d3/gameData.ts#L41
You can use it like `async getSeasonLeaderboard(seasonId: number, leaderboardId: string): Promise<ISeasonLeaderboard>`

**Comment by QuadDamn** [comment]
@skliffmueller I really appreciate that feedback!  I will be working to update the code base with your feedback.

I figured I was shorting the return type, but I wasn't sure how best to attack the problem.

All the best!

**Comment by QuadDamn** [comment]
@skliffmueller When I try to do as you prescribe above, I get that the following TS error: `Cannot find module 'gameData.d'.`.  I called the file `gameData.d.ts`.  It lives in the same directory as the `gameData.ts` file.  Thoughts on what I could be missing?  Do I need to update something in my `.tsconfig` to look for the type declarations in an additional directory?

**Comment by QuadDamn** [comment]
@skliffmueller Managed to figure my through the problem set.

1) Create a `@types` folder under the `src` directory.
2) Add the `@types` folder to the `tsconfig.json` by doing: 

```
{
  "compilerOptions": {
    ...
    "typeRoots" : [
      "./src/@types"
    ]
  }
}

3) In the respective non-type declaration file, I import it the exported types/interfaces by doing `import { ISeasonLeaderboard } from "types/d3GameData";`, which is the name of the declared module in the type declaration file.

4) Given that axios is being used, I had to add a type to the axios request so that the returned data follows that type/interface desgination.

```
    async getSeasonLeaderboard(seasonId: number, leaderboardId: string): Promise<ISeasonLeaderboard> {
        try {
            const response = await this.axios.get<ISeasonLeaderboard>(encodeURI(`${this.gameBaseUrlPath}/season/${seasonId}/leaderboard/${leaderboardId}`));
            return response.data;
        } catch (error) {
            console.log(error);
            throw new Error(`Diablo 3 Game Data Error :: Error fetching the specified season leaderboard.`);
        }
    }
```

A bit more involved than what I was planning, but I get the need for the additional type safety.  This will be especially helpful for testing.

I am trying to figure out how to be able to still have the reusable `_handleApiCall` function, but the needing of the type prior to the axios calls makes it more difficult.

**Comment by skliffmueller** [comment]
Hey, sorry I didn't reply sooner, sometimes work consumes my life. I wanted to follow up on how to use the helper function while returning the correct response data types. Here is an example of how `_handleApiCall` would be used in D3:

`
class Diablo3GameData {
    private readonly axios: AxiosInstance;
    private readonly defaultAxiosParams: object;
    private readonly gameBaseUrlPath: string = '/data/d3';

    constructor(axiosInstance: AxiosInstance, defaultAxiosParams: object) {
        this.axios = axiosInstance;
        this.defaultAxiosParams = defaultAxiosParams;
    }
  /********************************
   * Private Class Helper Functions
   ********************************/
    // 'T' is used like a typings parameter in this context, which then can be used elsewhere
    async _handleApiCall<T>(apiUrl: string, errorMessage: string): Promise<T> {
        try {
            const response = await this.axios.get<T>(encodeURI(apiUrl), {
                params: {
                    ...this.defaultAxiosParams
                }});
            return response.data;
        } catch (error) {
            console.log(error);
            throw new Error(`Diablo 3 Game Data Error :: ${errorMessage}`);
        }
    }

    /**
     * Returns an index of available seasons.
     */
    async getSeasonIndex(): Promise<ISeasonIndex> {
        // Where you set ISeasonIndex as the _handleApiCall's constructor
        return await this._handleApiCall<ISeasonIndex>(
            `${this.gameBaseUrlPath}/season`, 
            `Error fetching the season index.`
        );
    }

}
`
