### ISSUE TITLE
Hi there!

### ISSUE THREAD

**Issue by lwojcik** [QuadDamn/battlenet-api-wrapper#2]
I saw your post on Battle.net community forums.

I built a few projects involving Battle.net APIs to support my Twitch extension for StarCraft II and learn new tech stack and released two NPM libraries. In other words I followed the same route as you seem to be going right now, but I barely focus on anything else than StarCraft II these days. :) Now I'm in love with TypeScript and looking to start a new project in a complete different area. 

Just letting you know if you need any help, questions or maybe project ideas I'll be happy to help or submit a pull request.

Glhf!

**Comment by QuadDamn** [comment]
Hey there @lwojcik!

I just need help with test coverage for the existing code base right now.  If you have the time/inclination, the thought was to just write Jest tests.  Feel free to just branch off and submit a PR of your work.

Thanks for any help you can provide!
